server:
  port: 8081

python:
  api:
    base-url: ${PYTHON_API_BASE_URL:http://localhost:8000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ragdb}
    username: ${SPRING_DATASOURCE_USERNAME:raguser}
    password: ${SPRING_DATASOURCE_PASSWORD:ragpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

app:
  jwt:
    secret: "${APP_JWT_SECRET:legal-rag-super-secret-key-2024-must-be-32-chars}"
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
